version: 0.2
phases:
    install:
        runtime-versions:
            python: 3.11
        commands:
            - pip install --upgrade pip
    # Install dependencies needed for running the static analysis - this is not requirement as pylint is already installed
            - pip install -r requirements.txt pylint
    pre_build:
        commands:
            - python --version
            - pylint --rcfile=pylint_configuration.ini $CODEBUILD_SRC_DIR/*.py
            - pylint --rcfile=pylint_configuration.ini $CODEBUILD_SRC_DIR/content_management/*.py
            - pylint --rcfile=pylint_configuration.ini $CODEBUILD_SRC_DIR/authentication/*.py
            - pylint --rcfile=pylint_configuration.ini $CODEBUILD_SRC_DIR/posts/*.py
artifacts:
    files:
        - '**/*'
